version: '3.8'

services:
  whos-my-buddy-db:
    image: postgres:16-alpine
    container_name: ${POSTGRES_DB}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/whosmybuddydata
volumes:
  pgdata:
